baseurl: "/wizliz"
url: "https://tolvubraut.github.io"
collections:
  companies:
    output: true
  news: 
    output: true
defaults:
  - scope:
      path: ""
      type: "companies"
    values:
      layout: "publisher"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "games"
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "news"
    values: 
      layout: "default"
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
sass: 
  style: compressed


      
